const SUPABASE_URL='https://rellsmuqjhcfhenjkbxa.supabase.co';
const SUPABASE_KEY='sb_publishable_PRT5-T0k-_AiSvy6lrJV-g_r7wLQjRk';
const {createClient}=supabase; const db=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,me=null,products=[],cart=[];
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2400)}
function err(e){return e?.message||'خطای نامشخص'}
async function rpc(fn,args={}){const r=await db.rpc(fn,args);if(r.error)throw r.error;return r.data}
async function loadMe(){me=await rpc('get_my_user_data'); if(!me?.profile) throw new Error('پروفایل کاربر یافت نشد'); $('storeName').textContent=me.store?.name||'BIZA MARKET'; if(me.profile.role==='admin') $('adminNav').classList.remove('hidden');}
async function ping(){const {error}=await db.from('stores').select('id').limit(1); $('dbStatus').textContent=error?'خطا در اتصال به دیتابیس':'دیتابیس متصل شد'; $('dbStatus').style.color=error?'var(--danger)':'var(--ok)'}
function showTab(name){document.querySelectorAll('.tab-page').forEach(x=>x.classList.add('hidden'));$(name+'Tab').classList.remove('hidden');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name)); if(name==='home')renderHome();if(name==='sale')renderSale();if(name==='inventory')renderInventory();if(name==='admin')renderAdmin()}
async function renderHome(){const d=await rpc('get_dashboard_summary');$('homeTab').innerHTML=`<div class="section"><div class="node-bg"></div><div class="page-title">داشبورد</div><div class="grid">${[['فروش امروز',d.today_revenue],['فاکتور امروز',d.today_invoices],['سود امروز',d.today_profit],['میانگین فاکتور',d.today_avg_invoice],['تعداد کالا',d.product_count],['موجودی',d.stock_qty],['کم‌موجودی',d.low_stock],['تمام‌شده',d.out_of_stock]].map(x=>`<div class="stat"><div class="n">${esc(Number(x[1]||0).toLocaleString('fa-IR'))}</div><div class="l">${x[0]}</div></div>`).join('')}</div></div>`}
async function loadProducts(){const {data,error}=await db.from('products').select('id,barcode,name,unit,is_active,current_purchase_price,current_sale_price').eq('is_active',true).order('name');if(error)throw error;products=data||[]}
async function renderInventory(){await loadProducts();$('inventoryTab').innerHTML=`<div class="page-title">انبار</div><div class="card cardpad"><div class="actions"><button id="newProductBtn">کالای جدید</button><button id="refreshInv" class="ghost">به‌روزرسانی</button></div><div id="invList" style="margin-top:14px"></div></div><div id="productForm" class="card cardpad hidden" style="margin-top:12px"></div>`;renderInvList();$('newProductBtn').onclick=()=>openProductForm();$('refreshInv').onclick=renderInventory}
function renderInvList(){const el=$('invList');if(!products.length){el.innerHTML='<div class="empty">کالایی ثبت نشده است.</div>';return}el.innerHTML=products.map(p=>`<div class="product-row"><div><b>${esc(p.name)}</b><br><small>${esc(p.barcode)} · ${esc(p.unit)}</small></div><button class="ghost" data-pid="${p.id}">ورود موجودی</button></div>`).join('');el.querySelectorAll('[data-pid]').forEach(b=>b.onclick=()=>openStockForm(b.dataset.pid))}
function openProductForm(){const f=$('productForm');f.classList.remove('hidden');f.innerHTML=`<h3>ثبت کالا</h3><div class="formgrid"><input id="pBarcode" placeholder="بارکد"><input id="pName" placeholder="نام کالا"><input id="pUnit" value="عدد" placeholder="واحد"><input id="pDesc" placeholder="توضیحات"><input id="pQty" type="number" min="0" step="0.001" placeholder="موجودی اولیه"><input id="pBuy" type="number" min="0" placeholder="قیمت خرید"><input id="pSell" type="number" min="0" placeholder="قیمت فروش"></div><div class="actions" style="margin-top:12px"><button id="scanProduct">اسکن بارکد</button><button id="saveProduct">ذخیره</button><button id="closePF" class="ghost">بستن</button></div>`;$('scanProduct').onclick=()=>scanInto('pBarcode');$('closePF').onclick=()=>f.classList.add('hidden');$('saveProduct').onclick=saveNewProduct}
async function saveNewProduct(){try{const id=await rpc('create_product',{p_barcode:$('pBarcode').value,p_name:$('pName').value,p_description:$('pDesc').value||null,p_unit:$('pUnit').value||'عدد'});const q=Number($('pQty').value||0);if(q>0)await rpc('add_stock',{p_product_id:id,p_quantity:q,p_purchase_price:Number($('pBuy').value||0),p_sale_price:Number($('pSell').value||0),p_note:null});toast('اطلاعات با موفقیت ذخیره شد');renderInventory()}catch(e){toast(err(e))}}
function openStockForm(pid){const f=$('productForm');f.classList.remove('hidden');f.innerHTML=`<h3>ورود Batch جدید</h3><div class="formgrid"><input id="sQty" type="number" min="0.001" step="0.001" placeholder="مقدار"><input id="sBuy" type="number" min="0" placeholder="قیمت خرید"><input id="sSell" type="number" min="0" placeholder="قیمت فروش"><input id="sNote" placeholder="یادداشت"></div><div class="actions" style="margin-top:12px"><button id="saveStock">ثبت Batch</button><button id="closeSF" class="ghost">بستن</button></div>`;$('closeSF').onclick=()=>f.classList.add('hidden');$('saveStock').onclick=async()=>{try{await rpc('add_stock',{p_product_id:pid,p_quantity:Number($('sQty').value),p_purchase_price:Number($('sBuy').value),p_sale_price:Number($('sSell').value),p_note:$('sNote').value||null});toast('Batch ثبت شد');renderInventory()}catch(e){toast(err(e))}}}
async function renderSale(){await loadProducts();$('saleTab').innerHTML=`<div class="page-title">فروش</div><div class="card cardpad"><div class="actions"><button id="scanSale">اسکن بارکد</button><input id="saleBarcode" placeholder="بارکد را وارد کنید" style="max-width:320px"></div><div id="saleProductList" style="margin-top:14px"></div></div><div class="card cardpad" style="margin-top:12px"><h3>سبد فروش</h3><div id="cartList"></div><div class="formgrid" style="margin-top:12px"><input id="discount" type="number" min="0" value="0" placeholder="تخفیف"></div><div class="actions" style="margin-top:12px"><button id="checkout">ثبت فروش</button></div></div>`;$('scanSale').onclick=()=>scanInto('saleBarcode');$('saleBarcode').oninput=e=>findByBarcode(e.target.value);$('checkout').onclick=checkout;renderProductChoices();renderCart()}
async function findByBarcode(v){if(!v)return;const p=products.find(x=>x.barcode===v.trim());if(p)await addProductToCart(p.id);else toast('کالا پیدا نشد')}
function renderProductChoices(){const el=$('saleProductList');el.innerHTML=products.map(p=>`<div class="product-row"><div><b>${esc(p.name)}</b><br><small>${esc(p.barcode)} · ${Number(p.current_sale_price||0).toLocaleString('fa-IR')} تومان</small></div><button class="ghost" data-add="${p.id}">افزودن</button></div>`).join('');el.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addProductToCart(b.dataset.add))}
async function addProductToCart(pid){const {data,error}=await db.from('inventory_batches').select('id,product_id,remaining_quantity,purchase_price,sale_price,created_at').eq('product_id',pid).gt('remaining_quantity',0).order('created_at');if(error)return toast(err(error));if(!data?.length)return toast('موجودی کافی نیست');cart.push({product_id:pid,batches:data});renderCart()}
function renderCart(){const el=$('cartList');if(!el)return;if(!cart.length){el.innerHTML='<div class="empty">سبد خالی است.</div>';return}el.innerHTML=cart.map((c,i)=>{const p=products.find(x=>x.id===c.product_id);return `<div class="cart-item"><div><b>${esc(p.name)}</b><br><select data-batch="${i}">${c.batches.map(b=>`<option value="${b.id}">${Number(b.sale_price).toLocaleString('fa-IR')} · موجودی ${Number(b.remaining_quantity).toLocaleString('fa-IR')}</option>`).join('')}</select></div><input data-qty="${i}" type="number" min="0.001" step="0.001" value="1"><button class="ghost" data-del="${i}">×</button></div>`}).join('');el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.del),1);renderCart()})}
async function checkout(){try{const items=cart.map((c,i)=>({product_id:c.product_id,batch_id:document.querySelector(`[data-batch="${i}"]`).value,quantity:Number(document.querySelector(`[data-qty="${i}"]`).value)}));if(!items.length)return toast('سبد خالی است');const r=await rpc('create_sale',{p_items:items,p_discount:Number($('discount').value||0)});toast(`فاکتور ${r.invoice_number} ثبت شد`);cart=[];renderSale()}catch(e){toast(err(e))}}
async function renderAdmin(){if(me?.profile?.role!=='admin'){showTab('home');return}const {data:stores}=await db.from('stores').select('id,name,code,status').order('name');const {data:profiles}=await db.from('profiles').select('id,full_name,username,role,is_active,store_id').order('created_at',{ascending:false});$('adminTab').innerHTML=`<div class="page-title">پنل مدیریت</div><div class="card cardpad"><h3>فروشگاه‌ها</h3><div class="actions"><input id="storeNameIn" placeholder="نام فروشگاه"><input id="storeCodeIn" placeholder="کد"><button id="createStoreBtn">ایجاد فروشگاه</button></div><div class="table-wrap" style="margin-top:12px"><table class="table"><tr><th>نام</th><th>کد</th><th>وضعیت</th></tr>${(stores||[]).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.code)}</td><td>${esc(s.status)}</td></tr>`).join('')}</table></div></div><div class="card cardpad" style="margin-top:12px"><h3>کاربران</h3><div class="table-wrap"><table class="table"><tr><th>نام</th><th>نام کاربری</th><th>نقش</th><th>فعال</th></tr>${(profiles||[]).map(p=>`<tr><td>${esc(p.full_name)}</td><td>${esc(p.username)}</td><td>${esc(p.role)}</td><td>${p.is_active?'بله':'خیر'}</td></tr>`).join('')}</table></div></div>`;$('createStoreBtn').onclick=async()=>{try{await rpc('create_store',{p_name:$('storeNameIn').value,p_code:$('storeCodeIn').value});toast('فروشگاه ایجاد شد');renderAdmin()}catch(e){toast(err(e))}}}
async function scanInto(inputId){const ret=`${location.origin}${location.pathname}?result={RESULT}`;const url='binaryeye://scan?ret='+encodeURIComponent(ret);sessionStorage.setItem('biza_scan_input',inputId);sessionStorage.setItem('biza_scan_open','1');window.location.href=url;}
function consumeScan(){const q=new URLSearchParams(location.search),result=q.get('result');if(result){const id=sessionStorage.getItem('biza_scan_input');if(id&&$(id)){$(id).value=result;$(id).dispatchEvent(new Event('input',{bubbles:true}));}history.replaceState({},'',location.pathname);sessionStorage.removeItem('biza_scan_input')}}
async function boot(s){session=s;if(!s){$('loginView').classList.remove('hidden');$('mainView').classList.add('hidden');return}try{await loadMe();$('loginView').classList.add('hidden');$('mainView').classList.remove('hidden');await ping();showTab('home');consumeScan()}catch(e){console.error(e);await db.auth.signOut();$('loginError').textContent=err(e)}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{let email=$('loginId').value.trim();if(!email.includes('@'))email=await rpc('get_login_email',{p_username:email});const {data,error}=await db.auth.signInWithPassword({email,password:$('loginPassword').value});if(error)throw error;await boot(data.session)}catch(e){$('loginError').textContent=err(e)}};
$('logoutBtn').onclick=()=>db.auth.signOut();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));window.addEventListener('online',()=>{$('networkStatus').textContent='Online'});window.addEventListener('offline',()=>{$('networkStatus').textContent='Offline'});db.auth.onAuthStateChange((_e,s)=>{if(s!==session)boot(s)});boot(null);
